/* Contains definitons of actions */

export const OPERATION_BEGIN = "OPERATION_BEGIN"
export const OPERATION_SUCCESS = "OPERATION_SUCCESS"
export const OPERATION_ERROR = "OPERATION_ERROR"

export const UPSERT_MATRIX = "UPSERT_MATRIX"
export const RENAME_MATRIX = "RENAME_MATRIX"
export const DELETE_MATRIX = "DELETE_MATRIX"

export const UPSERT_COMPOSITE = "UPSERT_COMPOSITE"
export const RENAME_COMPOSITE = "RENAME_COMPOSITE"
export const DELETE_COMPOSITE = "DELETE_COMPOSITE"
