/* Contains definitons of actions */

export const MULTIPLY_BEGIN = "MULTIPLY_BEGIN"
export const MULTIPLY_SUCCESS = "MULTIPLY_SUCCESS"
export const MULTIPLY_ERROR = "MULTIPLY_ERROR"

export const OPERATION_BEGIN = "OPERATION_BEGIN"
export const OPERATION_SUCCESS = "OPERATION_SUCCESS"
export const OPERATION_ERROR = "OPERATION_ERROR"

export const UPSERT_MATRIX = "UPSERT_MATRIX"
export const RENAME_MATRIX = "RENAME_MATRIX"
export const DELETE_MATRIX = "DELETE_MATRIX"

export const APPEND_LINE = "APPEND_LINE"